os: linux
dist: trusty

language: node_js

node_js:
  - 'lts/erbium'

before_script:
  - npm i -g gatsby-cli

script: gatsby build --prefix-paths

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: docs
  email: david.p.wood+travis-deploy@gmail.com
  name: Travis Deploy Bot
  on:
    branch: master
